### ISSUE TITLE
Mirror Stats - Daily stats filter by repo

### ISSUE THREAD

**Issue by lannonbr** [COSI-Lab/MirrorWebsite#12]
I think it may be cool to see the daily graph be able to be filtered down to repos so I can see for example the day by day amounts for something like Blender.

**Comment by jrddunbr** [comment]
I think we have this by now? We definitely have a pie chart.

**Comment by lannonbr** [comment]
Closing this issue as continued work for Mirror has migrated to https://github.com/COSI-Lab/Mirror
