### ISSUE TITLE
Hourly Bandwidth in GB, not TB.

### ISSUE THREAD

**Issue by jrddunbr** [COSI-Lab/MirrorWebsite#16]
https://github.com/COSI-Lab/MirrorWebsite/blob/ac38045a4480eef688e4037322778344a6d3df8b/js/stats.js#L291

This line needs to probably be modified from being TB to GB. I doubt our hourly stats are measured in TB per hour if our daily measure is only around 3-4 TB per day.

**Comment by lannonbr** [comment]
Fixed
