### ISSUE TITLE
Ampersands not evenly spaced

### ISSUE THREAD

**Issue by jrddunbr** [COSI-Lab/MirrorWebsite#5]
# In distributions.html:

There needs to be a space after the ampersand so that it formats properly. Also, you need to escape all of the ampersands (so see the top of the file at lines 43 and 55 as well.

## Solution
* Add spaces directly after the ampersand on lines 117, 138, 159, and 231
* Relace `&` with `&amp;` on lines 43, 55, 117, 138, 159, and 231

Yes, I'm aware this is trival. :D

**Comment by lannonbr** [comment]
Fixed.
